/**:
  ros__parameters:
    gimbal_name: gb # Name of the gimbal
    gimbal_frame_id: gb/_0/_1/_2 # Name of the gimbal frame
    gimbal_base_frame_id: gb # Name of the base frame of the gimbal
    gimbal_orientation_threshold: 0.05 # Threshold for the gimbal orientation
    tf_timeout_threshold: 2.0 # Default tf timeout (50ms)
